#baseurl: /seek

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@main

current_seek_version: "1.16.2"
current_docker_tag: "1.16"

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

title: "DataHub Documentation"
topnav_title: ""
instance_name: "DataHub"


exclude:
 - Gemfile*
 - .gitignore

permalink: /:categories/:year/:month/:day/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "help"
    values:
      sidebar: user_guide
  -
    scope:
      path: "tech"
    values:
      sidebar: technical_references

theme_variables:
  breadcrumb: true
  #git_host: GitHub
  #back_to_top: true
  #github_buttons:
  #  position: top
  #  edit_me: true
  #  open_issue: true
  #  history: true
  # toc:
  #   min_headings: 2
  #   headings: 'h2'
  topnav:
    theme: light
    brand_logo: images/datahub_logo.png
    #github: true
    #twitter: false
  theme_color: 8cddf6
# theme color is not working! Trying c23669 from RDMkit doesn't help

github:
  repository_url: https://github.com/seek4science/seek-documentation
  source:
    branch: main
